### ISSUE TITLE
Steuerklassen

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#143]
### Current and desired situation

Steuerklassen are an important part of the tax code for married couples. GETTSIM implicitly assumes Steuerklasse IV everywhere at present.

While Steuerklassen have transient effects until the tax declaration, they can have important impacts on household bargaining (https://dx.doi.org/10.1016/j.jpubeco.2019.104048) and they have a first-order impact on unemployment benefit payments (anything else?).  

### Proposed implementation

* Require columns `e_st_klasse` and `e_st_klasse_faktor`
* Provide a function that generates them with defaults of 1 / missing (singles) and 4 / 0.5 (couples) to keep current behaviour
* Make it a mandatory parameter for functions calculating income taxes at the individual level.

**Comment by Eric-Sommer** [comment]
Very important issue!

> Steuerklassen are an important part of the tax code for married couples. GETTSIM implicitly assumes Steuerklasse IV everywhere at present.

We currently simulate the income tax which is based on all income sources and determined after filing the tax claim (see #18). Steuerklassen do not matter for income taxation, but for the Lohnsteuer / withdrawal tax. Essentially, if you want allow Steuerklassen to matter, you have to deduct Lohnsteuer instead of income tax. This also means a slightly different deduction of social security contributions ( [Vorsorgepauschale](https://de.wikipedia.org/wiki/Vorsorgepauschale) versus [Vorsorgeaufwendungen](https://de.wikipedia.org/wiki/Sonderausgabe_(Steuerrecht)#Vorsorgeaufwendungen). In this case we would also need to consider whether to simulate income taxes on other income types (pensions, business, rental income).
 
> ... and they have a first-order impact on unemployment benefit payments (anything else?).

Parental Benefit

**Comment by hmgaudecker** [comment]
Re 1: I believe we will need both, hence the reference to individual income. Total taxes paid for a given year will not change. Thanks for the reminder re #18.

Re 2: how could I forget about that?

**Comment by Eric-Sommer** [comment]
> Total taxes paid for a given year will not change.

Yes they typically will because of splitting rule and because you can deduct more items for the income tax.

**Comment by hmgaudecker** [comment]
No, what I am trying to say is that it will not be an either/ or thing. The code we currently have will determine total taxes paid in a year. But we need more than that.
