### ISSUE TITLE
Automate aggregation of individual measures

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#281]
### Current and desired situation

Currently, the code contains several functions that aggregate individual transfers or taxes on the tax unit or household level (e.g. `kindergeld_m_hh`). 

The function definitions all look basically the same.

Would be pretty to somehow define these functions without repeating code.

### Proposed implementation

not sure yet

### Considered alternatives

**Comment by hmgaudecker** [comment]
I am not sure yet whether code clarity would be helped by replacing
```python
kindergeld_m.groupby(hh_id).sum()
```
by
```python
aggregate(series=kindergeld_m, level=hh_id, func="sum")
```
?

Or were you thinking of something else?\

**Comment by ChristianZimpelmann** [comment]
No, I was thinking about replacing the definitions of 10+ functions that aggregate individual measures (they do all the same thing) with some other way to define these functions in a less repetitive way.

But I am not sure if there is a good way to do that in Python (to define a list of similar functions).

Maybe this isn't possible in the current setting and we just stick to the current situation.

**Comment by hmgaudecker** [comment]
Ah, something like `sum_hh(var)`, which would take `kindergeld_m` as an input in the above and return `kindergeld_m_hh`? Sorry if I misunderstood -- are we only talking about sums?

This would reduce code indeed, which is always a good thing. The question for me would be whether there would be a nice and easy way to include that in the docs? I.e., I'd imagine there are quite a few variables that exist at a lower level of aggregation, but where you'd only ever want the aggregated version. If the latter is implicit and does not show prominently in the docs, I think the case would be tough.

**Comment by ChristianZimpelmann** [comment]
Yes, it is only about summing individual values on the tu or hh level.

**Comment by hmgaudecker** [comment]
Cool. I think it boils down to having the resulting variables nicely in the DAG / documentation then. Could also be a case for a decorator? @janosg ?

**Comment by hmgaudecker** [comment]
Thanks for pushing this, @ChristianZimpelmann !

**Comment by janosg** [comment]
Dynamically generating the functions or modifying them with a decorator is hard. Mainly because the argument names are so important for the DAG creation and dynamically generated functions would not have the right argument names. However, Christian and I had another idea. 

Currently there are two types of variables in gettsim:
1. Variables that are in the original dataset
2. Variables that are generated by a function

We propose to add a third type: Variables that are an aggregated version of another variable. Those variables would have to follow a naming scheme (`base_variable_hh` or `base_variable_tu` for household and tax-unit level variables, respectively) and could then be used as arguments of functions (or specified as targets) without providing functions that generate them. More flexible naming schemes are also possible (e.g. base_variable_groupby_variable) but maybe overkill. 

This would be very useful internally and for power users who specify completely new tax and transfer systems. It would not complicate anything for beginners, because it is strictly optional. The modification of the DAG Code would also be small.

If we get positive feedback here we could draft a GEP for this. Implementation would be by Christian and me.

**Comment by hmgaudecker** [comment]
Sounds good to me, thanks! 

Some comments:
- The naming scheme you describe should already be in place.
- Please write "sum" instead of "aggregation". Else we would need to include the aggregator in the new function's name and I'd buy into Christian's analysis that we are talking about sums only.
- Distinguishing this new case from case 2. seems like an implementation detail to me, but I do not have a strong opinion.
- The main issue for me is still to make sure this is nicely integrated in the documentation (clickable DAG in bokeh, list of variables). I'd imagine there are several cases where we are mostly thinking about the aggregated version, they need to be visible front and center.

**Comment by hmgaudecker** [comment]
This discussion prompted me to have a look at GEP-4. Instead of suggesting to merge it, I would actually encourage you guys to add a section. This seems a bit small for an entire GEP.

**Comment by janosg** [comment]
Yes, naming scheme is already there. 

The distinction is only relevant for implementation. The visualization in the DAG would be completely the same. 

Didn't know that #178  (GEP 4) is still open. Then we can just add it there.

**Comment by hmgaudecker** [comment]
> The distinction is only relevant for implementation. The visualization in the DAG would be completely the same.

Great. Then we just should not make a huge deal out of it.

> Didn't know that #178 (GEP 4) is still open.

Yes, so many things got stashed away over the past year. Good to see action picking up again!

**Comment by hmgaudecker** [comment]
Just thinking of the open GEP PRs again... Any updates on this one?

**Comment by ChristianZimpelmann** [comment]
Thanks for the reminder. Will pick it up during the next two weeks!
