### ISSUE TITLE
Make lagged policy parameters available

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#305]
### Current and desired situation

Some transfers are based on previous year's income. Therefore, sometimes access to previous year's policy parameters is necessary.

### Proposed implementation

- Add a processing step within `set_up_policy_environment ` that pre-processes the parameters in the .yaml files such that also policy parameters of the previous year become available.
- Make those easily accesible within GETTSIM functions (e.g.  `ges_renten_vers_params_last_year`)

Comment by @hmgaudecker: 

> another example [where pre-processing might be helpful] would be the income tax function

**Comment by ChristianZimpelmann** [comment]
This functionality would be used for #275

**Comment by hmgaudecker** [comment]
> Some transfers are based on previous year's income. Therefore, sometimes access to previous year's policy parameters is necessary.

Careful, we are mixing two different things here now. Income would be on the data side, not much we can or should do other than asking users to pre-calculate some form of net income with the prior  year's parameters (thinking of ALG I, Elterngeld here).

> Thanks both! Indeed sounds like we may want to add a processing step that loads the parameters from t-1. No reason that the policy function parameters as specified in the yaml-files have to enter the policy_params directly without changes

> ### Proposed implementation
> 
>     * Add a processing step within `set_up_policy_environment ` that pre-processes the parameters in the .yaml files such that also policy parameters of the previous year become available.
> 
>     * Make those easily accesible within GETTSIM functions (e.g.  `ges_renten_vers_params_last_year`)


The [original thing](https://github.com/iza-institute-of-labor-economics/gettsim/pull/275#r740369910_) came up when a lot of **parameters** were just repeated in the yaml file. Rather than this error-prone duplication, we should just for 2021 read in the values for 2020 as well etc. 

> Comment by @hmgaudecker:
> 
> > another example [where pre-processing might be helpful] would be the income tax function

I meant this as an example where we also pre-process the data from the yaml file rather than just storing them in a dict without converting anything. Sorry for the confusion.

We should do this only for the parameters that we actually need in t, not as a default thing. Don't understand the context in the original example enough for why the parameters would be required there.

**Comment by ChristianZimpelmann** [comment]
> Careful, we are mixing two different things here now. Income would be on the data side, not much we can or should do other than asking users to pre-calculate some form of net income with the prior year's parameters (thinking of ALG I, Elterngeld here).

That was just thought as an introductory explanation why access to previous year's parameters is sometimes needed. But thanks for the clarification!

**Comment by ChristianZimpelmann** [comment]
> We should do this only for the parameters that we actually need in t, not as a default thing. 

Given that we only need it for one parameter, that sounds sensible.
