### ISSUE TITLE
Revise groups supported by GETTSIM

### ISSUE THREAD

**Issue by cpz-research** [iza-institute-of-labor-economics/gettsim#379]
### Current situation

Two groups: tax units and households

### Proposed implementation

- rename households (`_hh`) to bedarfsgemeinschaft (`_bg`)
- check for all transfers if they are calculated on the correct level (see e.g. #218 or #335  )

### Open Questions
- Do we need the concept of a core family?
- Do we need special treatment for wohngeld-Gemeinschaft?

**Comment by ChristianZimpelmann** [comment]
I thought a bit more about this issue and think we should for now only do the two points under "Proposed implementation".

- I think core family is not needed at the moment
- Wohngeld-Gemeinschaft might be interesting in the future, but then we would also need to make the Wohngeld vs ALG 2 Vorrang-Check more complex (`wohngeld_vorrang_hh`).

Do you agree, @Eric-Sommer @mjbloemer @hmgaudecker ?

**Comment by Eric-Sommer** [comment]
Isn't this:

> * check for all transfers if they are calculated on the correct level (see e.g. [Reduce calculation of wohngeld to right level #218](https://github.com/iza-institute-of-labor-economics/gettsim/issues/218) or [Calculate kinderzuschl_heizkosten_m on tax unit level #335](https://github.com/iza-institute-of-labor-economics/gettsim/issues/335)  )

inherently the same as this?

> * Do we need special treatment for wohngeld-Gemeinschaft?

**Comment by hmgaudecker** [comment]
Well, of course it does not need to be done in the same PR but it does concern the same issue of relations between rows of data, so we should at least get the conceptual point clear.

>    what about non biological parents or legal guardians? (Suggestion: also include them as elternteil_1)

I guess we do not care about biology at all. Or could there be cases where the, say, biological father pays alimony (or not, for that matter -> `unterhaltsvorschuss`) and the mother is living with a new partner, which is relevant for taxes and transfers? @mjbloemer @stichnoth @JuergenWiemers  (feel free to ping more knowledgeable people)

>  What about parents not living in the same household,

Distinguishing this would be precisely a point of such a structure. The `elternteil` would have a different `tu_id` / `bg_id`  

> or even being unobserved (there might be some underage children that live alone)?

Same here -- not sure what we could do with those and I don't think we can handle them at present, either?

> also include this variable for adults / persons that are non dependent children? (Suggestion: yes. Whether somebody is a dependent child should be decided internally based on age, income, working hours, etc., not by the user. However, currently we have the input variable kind)

This is the point indeed.

> Would it still be the case that children are grouped in the same tax unit as their parents? (This is currently the case, but doesn't seem correct in case they earn any income). 

This is an interesting case indeed. Can't really expect from the user to input valid tax units in that sense since they depend on policy environment. Would be a pain on many dimensions, particularly if working with discrete choice models and having 20-year-olds work or not... 

My first idea would be a "candidate" `tu_id` by the user and assigning a final one endogenously.

This is orthogonal to the question of `elternteil` though -- How do the Stata-models solve this beast?

> If yes, how about unmarried parents?

Endogeneity of tax unit revisited, only that it would not be unique...

**Comment by ChristianZimpelmann** [comment]
I like the idea of "candidate" tu_id. This would be what I called "core family" above. 

The alternative would be that tax units consists only of the (married) adult(s) and children are put in a separate tu. We would than use the additional information if the members of a tax unit have children, if the children live in the same household, and age and earnings of children to determine the taxes of the parent(s).

> only that it would not be unique...

What exactly do you mean?

**Comment by hmgaudecker** [comment]
> I like the idea of "candidate" tu_id. This would be what I called "core family" above

Ahh, then we should include it here.

> The alternative would be that tax units consists only of the (married) adult(s) and children are put in a separate tu. We would than use the additional information if the members of a tax unit have children, if the children live in the same household, and age and earnings of children to determine the taxes of the parent(s).

That would actually be cleaner from the perspective of the name, which remains confusing to me in its current meaning.

Will need to work through the cases how we assign
- `kindergeld`
- `kinderfreibetrag`
- `wohngeld` (?)

then depending on whether people live with their parents or not. Should actually work out fine. I am just not fully sure of the aggregates then (what do we call a household then etc.).

Care to get started with a bunch of test cases? I think that is what is needed in order to fix ideas.

> > only that it would not be unique...
> 
> What exactly do you mean?

If we require a tax unit for children eligible for kindergeld and each parent gets half of it, we would actually need two tax unit ids. But per the just-above, that probably is not required.

**Comment by ChristianZimpelmann** [comment]
Here some thougb(in addition to Bedarfsgemeinschaft insights about the implementation:

- having `elternteil_` as input variables seems like a good addition
- the two implementations of tax unit vs core family seem very similar. Seems to be rather a matter of taste unless we can use `core family` for some other welfare program (which is not the case AFAIK)

## Some notes about child-related transfers

- Kindergeld is always payed to only one parent (for separated parents the one in whose household the child lives). But both parents are entitled to half of it -> for separated parents, is typically offset against Unterhaltszahlungen.
- Kinderfreibetrag: both parents get one half. If one parent doesn't pay alimony, the other parent can apply to receive full Kinderfreibetrag.
- Günstigerprüfung done for both parents separately. One parent can get (half of) Kindergeld and the other (half of) Kinderfreibetrag. Question: How is it handled if parent in household gets full Kindergeld, but for parent in other household Kinderfreibetrag is "günstiger" does he/she just get the difference back?

## Implementation 1: core family

- Input variables:
  - core family identifier `cf_id` (in addition to Bedarfsgemeinschaft id). `cf` consists of: partnered adults + their dependent children in the same household
  - new input variables `elternteil_1` and `elternteil_2`.
- How to calculate ...
  - taxes: split `cf` into tax units based on marital status (and potentially info on `gemeinsam_veranlagt`). Each child gets their own tax unit.
  - `kinderfreibetrag`: Each `elternteil` gets half of `kinderfreibetrag`. If only one `elternteil`, gets full `kinderfreibetrag`. Question: what if `elternteil_2` exists, but is not in the data set?
  - `kindergeld`:
    - If parents in same core family: each parent gets one half (ignore that actually only payed out to one of them)
    - If parents separated: only payed to `elternteil` in the same core family. But Günstigerprüfung based on half of Kindergeld for both parents. Kindergeld is offset against Unterhaltszahlungen.

## Implementation 2: tax units

- Input variables:
  - tax unit identifier `tu_id` (in addition to Bedarfsgemeinschaft id). `tu` consists of: people which file taxes together (either one person or two married persons). Note that children are all in a separate tax unit.
  - new input variables `elternteil_1` and `elternteil_2`.
- How to calculate ...
  - taxes: use `tu_id` directly
  - `kinderfreibetrag`, `kindergeld`: same as for Implementation 1

**Comment by hmgaudecker** [comment]
Thanks, sounds great! 

Two points.
- Agreed that tax units is a poor name for what is being meant currently, keeps confusing the heck out of me. Maybe just keep `gemeinsam_veranlagt` or `_gv` as an identifier?
- I think we should call the variable `kindergeldempfänger_1` and  `kindergeldempfänger_2`. It is really about some financial construct rather than the biological/custodian relationship. Though identical in 99% of all cases, it is endogenous to policy changes.

**Comment by ChristianZimpelmann** [comment]
`kindergeldempfänger` sounds good! We just need to shorten it. `id_kindergeldempf_1` etc. would work.

I don't like `gemeinsam_veranlagt` as the name of a grouping variable though. It sounds quite strange to say an unmarried person is `gemeinsam_veranlagt` with himself/herself. I think tax unit actually fits quite well in this case and with the proposed changes it should be much less confusing as really only those subjects form a tax unit who file their taxes together (without their children).

**Comment by hmgaudecker** [comment]
I don't mind much. But I guess whether people find it confusing will depend a lot on history (hard to change definitions after being used to one usage for ten years or so) and whether it will live on in its IZA-Psi-MOD-guise in other models.

Maybe others could chime in here?

**Comment by ChristianZimpelmann** [comment]
After some discussion with @mjbloemer, I came up with these example households:

- In the second part of the table, after the empty column, I sketch how the calculation of `kindergeld` and `kinderfreibetrag` would be done with the new structure.
- a reason to use `id_elternteil` instead of `id_kindergeldempf_1` would be that the link will be also important for Betreuuungskosten (and potentially other tax-related matters), in addition to Kindergeld.


### Old: basic hh

| p_id | tu_id | hh_id | alter | bruttolohn_m | betreuungskost_m |
| ---- | ----- | ----- | ----- | ------------ | ---------------- |
| 1    | 1     | 1     | 40    | 3000         | 0                |
| 2    | 1     | 1     | 40    | 3000         | 0                |
| 3    | 1     | 1     | 10    | 500          | 0                |
| 4    | 1     | 1     | 2     | 0            | 250              |

### New: basic hh

| p_id | tu_id | hh_id | alter | id_elternteil_1 | id_elternteil_2 | bruttolohn_m | betreuungskost_m |     | kindergeld_basis_m | kindergeld_basis_eltern_m_tu | zu_verst_eink_ohne_kinderfreib_tu | zu_verst_eink_mit_kinderfreib_tu | eink_st_abz_betreuungskost_m_tu |
| ---- | ----- | ----- | ----- | --------------- | --------------- | ------------ | ---------------- | --- | ------------------ | ---------------------------- | --------------------------------- | -------------------------------- | ------------------------------- |
| 1    | 1     | 1     | 40    |                 |                 | 3000         | 0                |     |                    | 438                          | 72000                             | 55200                            | 250                             |
| 2    | 1     | 1     | 40    |                 |                 | 3000         | 0                |     |                    | 438                          | 72000                             | 55200                            | 250                             |
| 3    | 2     | 1     | 10    | 1               | 2               | 500          | 0                |     | 219                |                              | 6000                              | 6000                             | 0                               |
| 4    | 3     | 1     | 2     | 1               | 2               | 0            | 250              |     | 219                |                              | 0                                 | 0                                | 0                               |

### New: unmarried parents

| p_id | tu_id | hh_id | alter | id_elternteil_1 | id_elternteil_2 | bruttolohn_m | betreuungskost_m |     | kindergeld_basis_m | kindergeld_basis_eltern_m_tu | zu_verst_eink_ohne_kinderfreib_tu | zu_verst_eink_mit_kinderfreib_tu | eink_st_abz_betreuungskost_m_tu |
| ---- | ----- | ----- | ----- | --------------- | --------------- | ------------ | ---------------- | --- | ------------------ | ---------------------------- | --------------------------------- | -------------------------------- | ------------------------------- |
| 1    | 1     | 1     | 40    |                 |                 | 3000         | 0                |     |                    | 219                          | 36000                             | 27600                            | 125                             |
| 2    | 2     | 1     | 40    |                 |                 | 3000         | 0                |     |                    | 219                          | 36000                             | 27600                            | 125                             |
| 3    | 3     | 1     | 10    | 1               | 2               | 500          | 0                |     | 219                |                              | 6000                              | 6000                             | 0                               |
| 4    | 4     | 1     | 2     | 1               | 2               | 0            | 250              |     | 219                |                              | 0                                 | 0                                | 0                               |

### New: single parent with alimony paying father in different household

| p_id | tu_id | hh_id | alter | id_elternteil_1 | id_elternteil_2 | bruttolohn_m | betreuungskost_m |     | kindergeld_basis_m | kindergeld_basis_eltern_m_tu | zu_verst_eink_ohne_kinderfreib_tu | zu_verst_eink_mit_kinderfreib_tu | eink_st_abz_betreuungskost_m_tu |
| ---- | ----- | ----- | ----- | --------------- | --------------- | ------------ | ---------------- | --- | ------------------ | ---------------------------- | --------------------------------- | -------------------------------- | ------------------------------- |
| 1    | 1     | 1     | 40    |                 |                 | 3000         | 0                |     |                    | 108.5                        | 36000                             | 31800                            | 125                             |
| 2    | 2     | 1     | 10    | 1               | 3               | 500          | 250                |     | 219                |                              | 6000                              | 6000                             | 0                               |
| 3    | 3     | 2     | 40    |                 |                 | 3000         | 0                |     |                    | 108.5                        | 36000                             | 31800                            | 125                               |

### New: adult "children"

| p_id | tu_id | hh_id | alter | in_ausbildung | id_elternteil_1 | id_elternteil_2 | bruttolohn_m | arbeitsstunden_w | betreuungskost_m |     | kindergeld_basis_m | kindergeld_basis_eltern_m_tu | zu_verst_eink_ohne_kinderfreib_tu | zu_verst_eink_mit_kinderfreib_tu | eink_st_abz_betreuungskost_m_tu |
| ---- | ----- | ----- | ----- | ------------- | --------------- | --------------- | ------------ | ---------------- | ---------------- | --- | ------------------ | ---------------------------- | --------------------------------- | -------------------------------- | ------------------------------- |
| 1    | 1     | 1     | 40    | False         |                 |                 | 3000         | 40               | 0                |     |                    | 438                          | 72000                             | 55200                            | 0                               |
| 2    | 1     | 1     | 40    | False         |                 |                 | 3000         | 40               | 0                |     |                    | 438                          | 72000                             | 55200                            | 0                               |
| 3    | 2     | 1     | 19    | False         | 1               | 2               | 0            | 0                | 0                |     |                    |                              |                                   |                                  | 0                               |
| 3    | 2     | 1     | 19    | True          | 1               | 2               | 0            | 0                | 0                |     | 219                |                              |                                   |                                  | 0                               |
| 3    | 2     | 1     | 20    | True          | 1               | 2               | 500          | 15               | 0                |     | 219                |                              | 6000                              | 6000                             | 0                               |
| 3    | 2     | 1     | 20    | True          | 1               | 2               | 1000         | 25               | 0                |     |                    |                              | 12000                             | 12000                            | 0                               |

**Comment by hmgaudecker** [comment]
Excellent, thanks to both of you! 

> * In the second part of the table, after the empty column, I sketch how the calculation of `kindergeld` and `kinderfreibetrag` would be done with the new structure.

Cool, thanks, this is very helpful.

> * a reason to use `id_elternteil` instead of `id_kindergeldempf_1` would be that the link will be also important for Betreuuungskosten (and potentially other tax-related matters), in addition to Kindergeld.

That sounds sensible, however the reason I'd like a legal term are corner cases like a kid getting adopted after some time in a panel etc. -- would be strange to change a variable `elternteil` then. E.g., look at this from BKGG:

 

> Als Kinder werden auch berücksichtigt
> 
> 1.    vom Berechtigten in seinen Haushalt aufgenommene Kinder seines Ehegatten oder Lebenspartners,
> 2.    Pflegekinder (Personen, mit denen der Berechtigte durch ein familienähnliches, auf Dauer berechnetes Band verbunden ist, sofern er sie nicht zu Erwerbszwecken in seinen Haushalt aufgenommen hat und das Obhuts- und Pflegeverhältnis zu den Eltern nicht mehr besteht),
> 3.    vom Berechtigten in seinen Haushalt aufgenommene Enkel.

I would not want to start labeling the grandparents `elternteil` because they are eligible for `kindergeld`.

> * in the last example in which children no longer eligible for `kindergeld` live together with their parents, I am not sure if they should still be part of the same household/`hh_id`. But that is a different question.

As long as we call it household, for sure. (basically) def of household is sharing a kitchen, period.

**Comment by ChristianZimpelmann** [comment]
> One test case to add is when we do not observe the partner as noted https://github.com/iza-institute-of-labor-economics/gettsim/issues/379#issuecomment-1145790180 by @ChristianZimpelmann

Thanks! I added the case above.

**Comment by ChristianZimpelmann** [comment]
Cross-linking #270 here. 

We can probably use the child-parent link to generate the variable `alleinerz` (child lives in same household, and person is the only parent of that child living in the household). 

But need to check whether this is indeed the definition used for taxes and transfers.

**Comment by ChristianZimpelmann** [comment]
> What do you mean by "we don't know" ? The user needs to make an assumption.

I am still thinking about the example households above. There, we are the ones making assumptions.

But I agree that GETTSIM should just allow for both possibilities and then let the user decide.

**Comment by hmgaudecker** [comment]
> > What do you mean by "we don't know" ? The user needs to make an assumption.
> 
> I am still thinking about the example households above. There, we are the ones making assumptions.

Ahhhh, apologies, I thought we were having a general discussion :smile: 

To the extent the example households become testcases, I guess we should eventually have them both ways.

**Comment by ChristianZimpelmann** [comment]
I would like to tackle this issue rather soon. We should allow at least for unmarried parents.

One possibility to do so without introducing `elternteil_`-variables would be as follows:

### New: unmarried parents

| p_id | tu_id | cf_id | alter | kind  | bruttolohn_m | betreuungskost_m |     | kindergeld_basis_m | kindergeld_basis_eltern_m_tu | zu_verst_eink_ohne_kinderfreib_tu | zu_verst_eink_mit_kinderfreib_tu | eink_st_abz_betreuungskost_m_tu |
| ---- | ----- | ----- | ----- | ----- | ------------ | ---------------- | --- | ------------------ | ---------------------------- | --------------------------------- | -------------------------------- | ------------------------------- |
| 1    | 1     | 1     | 40    | False | 3000         | 0                |     |                    | 219                          | 36000                             | 27600                            | 125                             |
| 2    | 2     | 1     | 40    | False | 3000         | 0                |     |                    | 219                          | 36000                             | 27600                            | 125                             |
| 3    | 3     | 1     | 10    | True  | 500          | 0                |     | 219                |                              | 6000                              | 6000                             | 0                               |
| 4    | 4     | 1     | 2     | True  | 0            | 250              |     | 219                |                              | 0                                 | 0                                | 0                               |


- Introduce new grouping `core family` which consists of:
  - 1 tax unit of 1 adult (single parent), 2 tax units of 1 adults (unmarried parents), or 1 tax unit of 2 adults (married parents)
  - and an unlimited number of tax units consisting of (dependent) children
  
Implementation would be easier as we did not need to implement the `elternteil_` variables. But we would not (yet) allow for parents outside of the household of the child. While this will be a relevant feature at some point, I am not sure how often we would observe this in data anyway

**Comment by hmgaudecker** [comment]
Yes!
