### ISSUE TITLE
Decide on variables

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#41]
### Current and desired situation

We need to decide which variables to be mandatory and which can either be assumed or if they appear only in a nonrelevant calculation( `m_imputedrent` in gross_income) can be left out. Furthermore there are variables right now, which can be computed from basic household data(`hhsize`, `child_num_tu` etc.)

### Proposed implementation

Catch in the beginning missing variables and either alert user or assume fill values, but still alert user.

### Considered alternatives

- Make all variables mandatory

**Comment by hmgaudecker** [comment]
I strongly favor the alternative. Let the user be explicit about this. 

We should, however, document eventually how to prepare various datasets and what sensible default values would be if a variable cannot be reasonably prepared. Andreas Peichl mentioned that something like this exists for TAXSIM (? or Euromod?). @mjbloemer, would you know a reference from the top of your head? 

As for internal function calls, the goal is make everything usable from [CuDF](https://github.com/rapidsai/cudf) eventually. In order to use something like apply_grouped on [this](https://docs.rapids.ai/api/cudf/stable/) page. We will need to think through exactly how to make it work, but for now we should definitely strive to call functions only with the minimal necessary subset of columns of df.

**Comment by Eric-Sommer** [comment]
potentially stupid, slightly off-topic question: If we are using CuDF, can "standard" users with a CPU make use of the package at all?

**Comment by CruelChris** [comment]
For EUROMOD, there is a document with modelling conventions: https://www.euromod.ac.uk/publications/euromod-modelling-conventions
It has info on variable names, values for missings or N/A etc. 

There is more detailed information for every input dataset in its "DRD file" (Data  Requirement  Document). The default data for EUROMOD are derived from EU-SILC, and the DRD files are Excel tables that specify how each variable has been derived from its SILC source.

**Comment by Eric-Sommer** [comment]
Hi @CruelChris  ;)

I don't know TAXSIM, but I'm pretty sure Euromod does not fill columns if they are not there. The error message "row too short" is what you see as a beginner pretty ofen. Their case is however somewhat different than ours as their input data are standardized and shipped along with the model.

**Comment by CruelChris** [comment]
Indeed, the EUROMOD case is a bit different as the datasets basically come with the model, although there are also attempts to use it with different datasets (HFCS based, if I'm not mistaken).

EUROMOD has default values in case a variable is not there or missing, but it is not very explicit about it, I think.

**Comment by hmgaudecker** [comment]
Welcome, @CruelChris! And thanks for all your replies. 

I think that is broadly the way to go. It is much better to require the user to make (guided) assumptions as opposed to letting her find out what we think are sensible defaults or just ignore stuff. 

I envisage that we would define a set of standard functions that would provide graceful error messages à la 

```python
f"""The function {func_name} requires that all variables that matter for its result
be specified. The dataset you passed in contains columns: 

    {'    '.join(sorted(df.columns))}

The dataset is missing the columns:

    {'    '.join(sorted(missing_columns))}

Please see the documentation of the function at https://gettsim.readthedocs.io/[version]/apidocs/ 
for the precise interface and https://gettsim.readthedocs.io/[version]/preparing_dataselts.html for 
setting up typical datasets and potential default values if your dataset misses certain columns.
"""

We will just need to write that once.

**Comment by hmgaudecker** [comment]
> potentially stupid, slightly off-topic question: If we are using CuDF, can "standard" users with a CPU make use of the package at all?

Sure, given that I am pretty much the only economist using GPUs seriously so far, this is the way to go for widespread adoption of GETTSIM :-)

Sorry, could not resist it (wink).  

The idea is to write all the functions in such a way that we can use Pandas or CuDF interchangeably. The highest-level function will require different flavours, but all the internal machinery should be able to figure out whether it is called with a `pd.DataFrame` or a `cudf.DataFrame`. 

That is why I have been pushing so hard on working on the household/tax unit level rather than an entire dataset.

**Comment by hmgaudecker** [comment]
> The documentation should also indicate for some variables the set and domain of valid values. 

Good point.

> E.g. 1.8 is not a valid value for the number of children (there might be applications that do things like that).

For that particular case, I believe we will actually require them to be specified as separate persons.

**Comment by hmgaudecker** [comment]
> Catch in the beginning missing variables and [raise an error in case of invalid data]

Do we do this now?

**Comment by hmgaudecker** [comment]
This seems to be taken care of now with the DAG? @MaxBlesch @tobiasraabe ?

**Comment by hmgaudecker** [comment]
This is taken care of by the DAG in 0.3. We can add a separate layer doing some educated guessing at some point, but that seems orthogonal to the discussion here.
