### ISSUE TITLE
Minimum income check Wohngeld eligibility

### ISSUE THREAD

**Issue by mjbloemer** [iza-institute-of-labor-economics/gettsim#592]
There is an income check for Wohngeld. I think this is not implemented yet.

**Comment by mjbloemer** [comment]
Some snippets from our documentation:

> Laut 15.01 ff. der Verwaltungsvorschriften zum § 15 WoGG hat die Behörde zu prüfen, ob die Einnahmen der Haushaltsmitglieder auch nach Abzug von Aufwendungen ausreichen, um den Lebensunterhalt der zu berücksichtigenden Haushaltsmitglieder zu bestreiten. Wird das Mindesteinkommen nicht erreicht, kann kein Wohngeld bezogen werden (dann SGB II Leistungen).

> Notwendiges Mindesteinkommen um Wohngeldanspruchsberechtigt zu sein. Die Einnahmen müssen die KdU, sowie ggf. die Beiträge zur Kranken- und Pflegeversicherung oder zur Altersvorsorge nach § 16 S. 2 WoGG und rund 80% des Bedarfs nach SGB XII decken.

> Alle Einkommensquellen inklusive Kindergeld und Kinderzuschlag gemäß §12a Nr. 2 SGB II        (siehe auch BMI Erlass vom 11.03.2020), sowie Unterhaltskostenvorschuss (§ 14 Abs. 2 Nr. 21 WoGG).

**Comment by ChristianZimpelmann** [comment]
Thanks! Just two further remarks:

- This case is for example relevant if household wealth exceeds the limit of Bürgergeld, but not the one of Wohngeld.
- The 80% rule is also referred to [here](https://www.wohngeld.org/mindesteinkommen/)

**Comment by MImmesberger** [comment]
Quick legislative summary:

The Mindesteinkommen for Wohngeld is regulated in [VwV 15.01 ff § 15 WoGG](https://www.verwaltungsvorschriften-im-internet.de/bsvwvbund_28062017_SWII4.htm). The Mindesteinkommen is computed as

1.0 * (
SGB II Regelbedarf of the wohngeldrechtlicher TeilHH
(+ Mehrbedarfe)
)

Now the Wohngeldstelle can make a discretionary judgment if the applicant does not meet the Mindesteinkommen:
1. Savings may partly cover the Regelbedarf, which makes the applicant eligible again
2. The Wohngeldstelle may reduce the Regelsatz by 20% (but not KdU and not private insurance contributions). As I understand it, the idea is that this is because of different price levels in different regions.

Because both exceptions are discretionary judgements, I would not implement them now.

The definition of income is correct, as stated in the [BMI Erlass](https://fragdenstaat.de/dokumente/7450-20200311-bmi-erlass-sw-ii-4_72307_230-plausibiltatsprufung/?page=1)
