### ISSUE TITLE
Misleading error message when a root node with possible time conversion is missing

### ISSUE THREAD

**Issue by JonasSchernich** [iza-institute-of-labor-economics/gettsim#621]
### Bug description
The following error came up after changing the calculation of Elterngeld by taking selbst_eink into account:

**E           ValueError: The DAG contains one or more cycles:
E           
E           [
E               "['eink_selbst_m', 'eink_selbst_y']",
E           ]**

The error could be fixed by adding the selbst_eink_m into the tests, however to me this solution does not appear to be appropriate for that error message.

---

#### Code Sample, a copy-pastable example
example code from file hh_id_2.yaml(same thing for other eltergeld testf iles):
code generating the issue:
```python
    bruttolohn_m:
      - 1800.0
    bruttolohn_vorj_m:
      - 1800.0
```
code not generating it:
```python
    bruttolohn_m:
      - 1800.0
     eink_selbst_m:
      - 0.0
    bruttolohn_vorj_m:
      - 1800.0
```

#### Problem description

I don't see how fixing the test files can solve the issue specified above, since no loop was stopped (as far as I can tell)

**Comment by hmgaudecker** [comment]
Thanks for the report! Just a clarification: The error message refers to a cycle in the DAG performing the computations, not a loop in Python code.

The error message should read: 

```
E           ValueError: The following data columns are missing.
E           
E           [
E               "m_elterngeld",
E           ]
```

Running `pytest src/_gettsim_tests/test_elterngeld.py --pdb` shows:
```
(Pdb++) dag.edges
OutEdgeView([
    ('eink_selbst_m', 'elterngeld_nettoeink_m'),
    ('eink_selbst_m', 'eink_selbst_y'),
    ('eink_selbst_y', 'eink_selbst_m'),
])
```
_(unrelated components omitted)_ So the reason is that we generate time conversions for `eink_selbst_X` both ways for $X \in \{m, y\}$. Usually we would remove the one we do not need again, but this does not seem to happen here because `eink_selbst_m` is missing. 

@lars-reimann, could you look into this?  [Here](https://github.com/iza-institute-of-labor-economics/gettsim/pull/619/commits/2ee1f9e6562c90cbc15c4d4f15b261d3072d708f) is the commit that fixed it in the PR. The version before that could be the testcase, although one could reduce it to a minimum, too. Thanks!
