### ISSUE TITLE
BUG: `piecewise_polynomial` ignores intercepts except for the first one

### ISSUE THREAD

**Issue by nafetsk** [iza-institute-of-labor-economics/gettsim#629]
### Bug description

The function [check_intercepts](https://github.com/iza-institute-of-labor-economics/gettsim/blob/f1ff0c0122c81da29d5b24e145321981a31460ea/src/_gettsim/piecewise_functions.py#L245C1-L290C22) responsible for preparing the intercepts for piecewise functions is not working properly in case intercepts are supplied for every part of the function. In that case the whole array is overwritten with the first intercept. We were confronted with that issue while working on #577  but apparently other piecewise functions should have encountered the same problem. 
For example in [eink_st.yaml](https://github.com/iza-institute-of-labor-economics/gettsim/blob/f1ff0c0122c81da29d5b24e145321981a31460ea/src/_gettsim/parameters/eink_st.yaml#L229C1-L266C38)

#### Proposed solution
The problem can be fixed by adding a condition checking for that case and preventing the overwriting. 

```python
def check_intercepts(
    parameter_dict, parameter, lower_thresholds, upper_thresholds, rates, keys
):
    """Check and transfer raw intercepte data. If necessary create intercepts.

    Transfer and check raw rates data, which needs to be specified in a
    piecewise_polynomial layout in the yaml file.

    Parameters
    ----------
    parameter_dict
    parameter
    lower_thresholds
    upper_thresholds
    rates
    keys

    Returns
    -------

    """
    intercepts = numpy.zeros(len(keys))
    count_intercepts_supplied = 1

    if "intercept_at_lower_threshold" not in parameter_dict[0]:
        raise ValueError(f"The first piece of {parameter} needs an intercept.")
    else:
        intercepts[0] = parameter_dict[0]["intercept_at_lower_threshold"]
        # Check if all intercepts are supplied.
        for interval in keys[1:]:
            if "intercept_at_lower_threshold" in parameter_dict[interval]:
                count_intercepts_supplied += 1
                intercepts[interval] = parameter_dict[interval][
                    "intercept_at_lower_threshold"
                ]
        if (count_intercepts_supplied > 1) & (count_intercepts_supplied != len(keys)):
            raise ValueError(
                "More than one, but not all intercepts are supplied. "
                "The dictionaries should contain either only the lowest intercept "
                "or all intercepts."
            )
        elif count_intercepts_supplied == len(keys):
            pass

        else:
            intercepts = create_intercepts(
                lower_thresholds, upper_thresholds, rates, intercepts[0]
            )
    return intercepts
```

**Comment by hmgaudecker** [comment]
> I think this is related to https://github.com/iza-institute-of-labor-economics/gettsim/issues/353. (Haven't thought it completely through though)

Most definitely! Thanks for the good memory!

**Comment by hmgaudecker** [comment]
I think we learned from here that we had initially thought about `piecewise_polynomial` to have jumps, contrary to what I had argued in #353

The main learning from there is to not blindly apply `piecewise_polynomial` just because it is there.
- for things that only vary at the parameter level (=not with individual data, like the gradual change in tax deductions for old age provision), don't use it at all
- for piecewise constant functions, use `np.searchsorted` (should be much faster)

**Comment by nafetsk** [comment]
> I think we learned from here that we had initially thought about `piecewise_polynomial` to have jumps, contrary to what I had argued in #353
> 
> The main learning from there is to not blindly apply `piecewise_polynomial` just because it is there.
> 
>     * for things that only vary at the parameter level (=not with individual data, like the gradual change in tax deductions for old age provision), don't use it at all
> 
>     * for piecewise constant functions, use `np.searchsorted` (should be much faster)

Thanks a lot for the feedback. In fact I didn’t know about `np.searchsorted` before. 
But considering the usecase in `em_rente` where we want to determine the `zurechnungszeitsgrenze_in_m` based on the individual retirement age I still think piecewise polynomial is the better choice since the `zurechnungszeitsgrenze_in_m` gradually increases from 2019 onwards.

**Comment by hmgaudecker** [comment]
Cool. Two things:
- Can you explain where the jumps come from?
- Off-topic here, but still: naming would have to be `m_zurechnungszeitsgrenze` because a suffix (or infix) `m` is reserved for variables that refer to monthly payments etc.

**Comment by amageh** [comment]
@hmgaudecker Thank you very much for the feedback! The jumps we want to account for are the changes in Zurechnungszeit that were implemented in pension reforms between 2014 and 2019. The current implementation we are working on in #577 is not accurate because it uses the Zurechnungszeit of the provided policy environment date instead of the Zurechungszeit of the policy environment when the start of the pension occurred.

As far as my understanding of `np.searchsorted` goes, it is limited to constant intercepts without a slope. This would only work for pensions with a start date up until 2019 since the Zurechnungszeit is increasing in tandem with the statutory retirement age from then on. 

We thought that `piecewise_polynomial' (with the small adjustment suggested in this issue) accommodates exactly this kind of use case, but maybe there is a better solution?

**Comment by hmgaudecker** [comment]
Makes perfect sense, I was just trying to understand! 

Will be an interesting case on how to best store parameters if you don't want to repeat the entire policy history each year a change occurs... Eventually should be fairly easy, for now I am not so sure.

**Comment by amageh** [comment]
I see, thank you very much for the input! For now the it seems like the suggested adjustment would be the best solution for our example, right? If that is the case I would suggest merging #630. Who should be preferable ask to review these types of PRs?

**Comment by TeBackh** [comment]
Probably to late, but also with the old function it was possible to implement jumps by implementing a steep increase between to periods.

**Comment by hmgaudecker** [comment]
Do you remember where we did that if we did? Should be changed, would become much clearer, I suppose.
