### ISSUE TITLE
ENH: test case seem to have three adults in a Bedarfsgemeinschaft

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#731]
the test case `src\_gettsim_tests\test_data\benefit_checks\2011\hh_id_5.yaml` consists of three adults, but the input variables seem to imply that they are all part of the same Bedarfsgemeinschaft. This should not be possible.

### Possibe solutions

- Delete this test case
- Adjust it to a proper test case in which Wohngeld is potentially paid for all three subjects on the hh-level, but ALG 2 is potentially paid in two separate Bedarfsgemeinschaften. Not sure though whether we already handle the Günstigerprüfung correctly (I don't even know how what is correct in such a case).

**Comment by hmgaudecker** [comment]
Just since I was confused for a bit. We pass `arbeitsl_geld_2_regelbedarf_m_bg`, which is the same for all adults. Cannot be the case if the Bedarfsgemeinschaft was created endogenously, but we don't check that.

I am sort of indifferent between the two solutions. In any case, we should at some point have test cases for households with multiple bg's. Not sure whether this one is a particularly good start, though. @MImmesberger, your call!

**Comment by MImmesberger** [comment]
Properly testing Wohngeld vs Bürgergeld makes sense once we fixed #710.

I will remove one adult from the test date, I think the test doesn’t rely on having three adults (might have missed something when looking at it quickly. Will take a proper look tomorrow).

**Comment by MImmesberger** [comment]
Closed via #751
