### ISSUE TITLE
Fill up documentation table on user data columns

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#91]
### Current and desired situation

The tables for [required input columns](https://gettsim.readthedocs.io/en/stable/getting-started.html#required-columns-in-input-data) and for [output columns](https://gettsim.readthedocs.io/en/stable/getting-started.html#columns-returned-by-the-simulator) are hardly filled in the second column.

It would be useful for picking up work on GEP 1 again and even more for my soon-to-be-drafted GEP 2 on internal data representation to have an overview of the actual names. @MaxBlesch, would be great if you could do that soonish with @Eric-Sommer's input as required.

### Proposed implementation

* Either just fill up the table for now. 
* In the long run, we probably want to have a YAML file that may have additional information structure (e.g., grouping of variables, units of measurement, ...)

I have no strong opinion for the moment what is easier; if it is simple to create a table from the YAML in the docs (is it, @tobiasraabe ?), maybe do it right immediately. Also saves the formatting stuff...

**Comment by tobiasraabe** [comment]
You cannot load yaml tables. I think there are two ways: First, convert the yaml to csv and use the csv directive. Secondly, write a custom directive `yaml-table` which takes the a yaml and converts it to a table.

1. - Convert the yaml to csv with a Python script and add it to the build step (via Make?) (https://stackoverflow.com/a/7259267). The csv file should be placed next to the source files of the docs or in a separated folder.
    - Use the `csv-table`-directive to embed the table (https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html#csv-files)
2. - Create a custom directive to load yaml files and convert them to a table (https://stackoverflow.com/a/18143318/7523785).

I am not sure how easy it is to do 2) as one has to learn some of the Sphinx internals. 1) Basically has everything, but I do not like how the script is added to the make file. Maybe one can add a function to the ``def setup(app)`` function in ``conf.py`` and let it execute the code for converting from yaml to csv. It is because I am not sure whether rtd uses the make command or the normal sphinx-build.

**Comment by hmgaudecker** [comment]
Agreed that 2. is nicer. Re 1. with make:  Would that even work on Windows?

A somewhat different approach would be to go for 1. but run it as part of the release process so that it becomes a plain source file from the point of view of the docs.

I think spending half a day on getting 2. to work would be worth it. If it is far from working, we can re-optimize.

**Comment by tobiasraabe** [comment]
You can easily install make on Windows via chocolatey.
